substitutions:
  device_name: esp32-cam-1
  friendly_name: ESP32-Cam

## Boilerplate

esphome:
  name: ${device_name}

esp32:
  board: esp32cam
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  domain: !secret wifi_domain
  fast_connect: True  # required for hidden networks
  ap:
    ssid: Fallback ${device_name}

captive_portal:

logger:
  #level: VERBOSE

api:
#  password: !secret esphome_secret

ota:
#  password: !secret esphome_secret


## Device-specific
## Using Hiletgo ESP32-CAM and Ai-Thinker camera from ESPHome page

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: 3D Printer Camera
  #resolution: 1024x768
  #idle_framerate: 0.1fps
  vertical_flip: false
  horizontal_mirror: false

output:
  - platform: ledc
    pin: GPIO4
    channel: 2 # channel 1 is used for esp32_camera
    id: gpio_4
light:
  - platform: monochromatic
    output: gpio_4
    name: $device_name body light
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO15
    num_leds: 7
    type: GRB
    name: $device_name ring light
    method: 
      type: esp32_i2s

